routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});


Route::group(['prefix' => 'dmback-end'], function () {
    Voyager::routes();
});

Auth::routes();

/**
 * Temp search routes before hooking it up with a dynamic search
 * algorythm
 */
    Route::any('/search', 'SearchController@search')->name('search');
    Route::get('/country/usa', 'SearchController@usa')->name('usa');
    Route::get('/country/zambian', 'SearchController@zm')->name('zm');
    Route::get('/country/british', 'SearchController@uk')->name('uk');
    Route::get('/country/newzealand', 'SearchController@newZ')->name('newz');

/**
 * Resources routes
 */
Route::resources([
    'movies' => 'MoviesController',
    'titles' => 'TitlesController',
    'people' => 'PeopleController',
    'peopleimages' => 'PeopleImagesController'
    ]);

/**
 * Saving titles from TMDB API
 */
    Route::get('/save', 'TitlesController@save')->name('save');
    Route::get('/update', 'TitlesController@saveDetailed')->name('saveDetailed');

/*
 *Fooetr Routes
 */
Route::get('/developer', function() {
    return view('footer.developer');
});

Route::get('/disclaimer', function(){
    return view('footer.legal.disclaimer');
})->name('disclaimer');

/**
 * Upload and store MyTitles and Images
 * 
 */
Route::get('/upload_mytitle', 'MytitlesController@create');
Route::post('/store_mytitle', 'MytitlesController@store')->name('storetitle');
Route::get('/upload_images/{mytitle_id}', 'ImagesController@create')->name('uploadimages');
Route::post('/store_images', 'ImagesController@store')->name('storeimages');
//Show MyTitle
Route::get('/show_mytitle/{mytitle}', 'MytitlesController@show')->name('showmytitle');

//People & People images routes

Route::get('/pip', function() {
    return view('people.index');
});

Route::get('/peopleimgs/{person}', 'PeopleimagesController@create')->name('peopleimages.create');

app/Models/Title.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Title extends Model
{

    /**
     * @see https://stackoverflow.com/a/25472319/470749
     * 
     * @param array $arrayOfArrays
     * @return bool
     */
    public static function insertIgnore($arrayOfArrays) {
        $static = new static();
        $table = with(new static)->getTable(); //https://github.com/laravel/framework/issues/1436#issuecomment-28985630
        $questionMarks = '';
        $values = [];
        foreach ($arrayOfArrays as $k => $array) {
            if ($static->timestamps) {
                $now = \Carbon\Carbon::now();
                $arrayOfArrays[$k]['created_at'] = $now;
                $arrayOfArrays[$k]['updated_at'] = $now;
                if ($k > 0) {
                    $questionMarks .= ',';
                }
                $questionMarks .= '(?' . str_repeat(',?', count($array) - 1) . ')';
                $values = array_merge($values, array_values($array));
            }
        }
        $query = 'INSERT IGNORE INTO ' . $table . ' (' . implode(',', array_keys($array)) . ') VALUES ' . $questionMarks;
        return DB::insert($query, $values);
    }

    /**
     * Relationships defined bellow
     */
    public function images()
    {
        return $this->hasMany('App\Models\Appdatum');
    }

    
    public function actors()
    {
        return $this->belongsToMany('App\Models\Actor', 'actor_title', 'title_id', 'actor_id');
    }

    public function themes()
    {
        return $this->belongsToMany('App\Models\Theme');
    }

    public function producers()
    {
        return $this->belongsToMany('App\Models\Producer', 'producer_title', 'producer_id', 'title_id');
    }

    public function languages()
    {
        return $this->belongsToMany('App\Models\Language');
    }
     /**
     * Director that made the title/film.
     */
    public function director()
    {
        return $this->belongsTo('App\Models\Director', 'id');
    }
    /**
     * Country that owns the title/film.
     */
    public function country()
    {
        return $this->belongsTo('App\Models\Country');
    }
    /**
     * Screenwriter that wrote the title/film.
     */
    public function script()
    {
        return $this->belongsTo('App\Models\Script', 'id');
    }

     /**
     * The Studio that made the title/film.
     */
    public function studio()
    {
        return $this->belongsTo('App\Models\Studio');
    }


     /**
     * Year in which title was made.
     */
    public function year()
    {
        return $this->belongsTo('App\Models\Year');
    }
}

app/Http/Controllers/TitlesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Title;
use App\Models\Mytitle;
use App\Models\Director;
use Illuminate\Http\Request;

class TitlesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $imageinfo = array('imgbaseurl' => 'https://image.tmdb.org/t/p/',
                            'imgsize' => 'w500');
        $titles = Title::all();
        $mytitles = Mytitle::all();
        return view('titles.index', ['titles' => $titles,'mytitles' => $mytitles])->with($imageinfo);

        /** Available Image sizes  "w92",w154,w185,w342,w500,w780,original,*/                
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    public function save()
    {
        ini_set('max_execution_time', 50);
        /**
         * Saving Dicover Movie Titles
         */
        $page = "8"; $rg = "NG";
        $apikey = "487fab9ddd30a7c5518757cf04cb2f2e";
        $discjson_data = file_get_contents("https://api.themoviedb.org/3/discover/movie?api_key=$apikey&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=$page");
        $discjson = json_decode($discjson_data,true);
        //echo $filmjson['results']['0']['poster_path'];
        $titlez = array();

        foreach($discjson['results'] as $result){
            $title = [

            'name' => $result['title'],
            'description' => $result['overview'],
            'poster' => $result['poster_path'],
            'tmdb_id' => $result['id'],
            //$genre_id = $result['genre_ids'];
            ];
            
            Title::insertIgnore([$title]);

           // array_push($titlez,$title);

            /**
             * Begin saving movie detailes withing a discover foreach
             */
                //////////////////////////////////////////////////////////////////
                            ini_set('max_execution_time', 300);
                            $titles = Title::all();
                            
                            foreach($titles as $title){

                                        $id = $title->tmdb_id;
                                        $apikey = "487fab9ddd30a7c5518757cf04cb2f2e";
                                        $detailedjson_data = file_get_contents("https://api.themoviedb.org/3/movie/$id?api_key=$apikey&language=en-US");
                                        $detailedjson = json_decode($detailedjson_data, true);
                                        $muviz = array();

                                        

                                    $title = Title::where('tmdb_id', $id)
                                        ->update([
                                            'budget' => $detailedjson['budget'],
                                            'popularity' => $detailedjson['popularity'],
                                            'release_date' => $detailedjson['release_date'],
                                            'revenue' => $detailedjson['revenue'],
                                            'runtime' => $detailedjson['runtime'],
                                            'vote_average' => $detailedjson['vote_average'],
                                            'vote_count' => $detailedjson['vote_count'],
                                            /** Arays down here */
                                            
                                            //'country' => $detailedjson['production_countries']['0']['name'],
                                            //'genres' => $detailedjson['genres']['1']['name'],
                                            //'languages' => $detailedjson['spoken_languages']['0']['name'],
                                            
                                        ]); 

                            } 
        /**
         * Finish saving detailes, and everything really.
         */
        }
        return ('Movies stored succesifully!!!!');

    }
        /**
         * Saving Detailed Movie Titles
         */
    public function saveDetailed()
    {
        ini_set('max_execution_time', 300);
        $titles = Title::all();
        
        foreach($titles as $title){

                    $id = $title->tmdb_id;
                    $apikey = "487fab9ddd30a7c5518757cf04cb2f2e";
                    $detailedjson_data = file_get_contents("https://api.themoviedb.org/3/movie/$id?api_key=$apikey&language=en-US");
                    $detailedjson = json_decode($detailedjson_data, true);
                    $muviz = array();

                $title = Title::where('tmdb_id', $id)
                    ->update([
                        'budget' => $detailedjson['budget'],
                        'popularity' => $detailedjson['popularity'],
                        'release_date' => $detailedjson['release_date'],
                        'revenue' => $detailedjson['revenue'],
                        'runtime' => $detailedjson['runtime'],
                        'vote_average' => $detailedjson['vote_average'],
                        'vote_count' => $detailedjson['vote_count'],
                        /** Arays down here */
                        'studio' => $detailedjson['production_companies']['0']['name'],
                        'country' => $detailedjson['production_countries']['0']['name'],
                        'genres' => $detailedjson['genres']['0']['name'],
                        //'languages' => $detailedjson['spoken_languages']['0']['name'],
                    ]);
        } 
        //return dd($movie);

        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Title $title, Mytitle $mytitle)
    {   
       
        /**
         * Decoding cast and showing them directly from TMDb
         */
        $id = $title->tmdb_id;
        $apikey = "487fab9ddd30a7c5518757cf04cb2f2e";
        $detailedjson_data = file_get_contents("https://api.themoviedb.org/3/movie/$id/credits?api_key=$apikey");
        $detailedjson = json_decode($detailedjson_data, true);
        $muviz = array();
        $actors = $detailedjson['cast'];

        $imgbaseurl = 'https://image.tmdb.org/t/p/w342';
        
        foreach($actors as $cast){
            $name = $cast['name'];
            $char = $cast['character'];
            $dp = $cast['profile_path'];
            $id = $cast['id'];
            //echo $cast['name'];
            $casta = $cast;
            
            $imageinfo = array('imgbaseurl' => 'https://image.tmdb.org/t/p/',
                                'imgsize' => 'w342',
                                'name' => $name,
                                'profile_path' => $dp,
                                'cast' => $detailedjson['cast'],);

            $title = Title::find($title->id);
                /** Get Similar movies by genera */
                $genere = $title->genres;
                    $similar = Title::where('genres','LIKE','%'.$genere.'%')->get();
                /** Get movies by the same studio */
                $studio = $title->studio;
                    $sameStudio = Title::where('studio','LIKE','%'.$studio.'%')->get();
                
            $mytitle = Mytitle::find($mytitle->id);

            return view('titles.show', ['title'=>$title,
                                        'similar'=>$similar,
                                        'sameStudio'=>$sameStudio,
                                        'mytitle'=>$mytitle])
                                        ->with($imageinfo);
                                        //->with($actors); //->with($cast);

         }
    } 
    
    /**
     * Show the form for editing the specified resource.
     *  
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/titles/index.blade.php
@extends('layouts.dm')

    <title>Discover - dm database</title>

        <link href="{{ asset('css/titles.css') }}" rel="stylesheet">
<style>
  /**
  *Custon css code goes here..
  */
    .sidenav {
        height: 100vh !important; /* Full-height: remove this if you want "auto" height */
        width: 160px; /* Set the width of the sidebar */
        position: absolute; /* Fixed Sidebar (stay in place on scroll) */
        z-index: 1; /* Stay on top */
        top: 0; /* Stay at the top */
        right: 0;
        background-color: #343d46;
        color: #FFF;
        padding-top: 20px;
    }
    .sidenav a {
        padding: 6px 8px 6px 16px;
        text-decoration: none;
        color: #c8ccce;
        display: block;
    }
    .main {
        margin-left: 150px; /* Same as the width of the sidebar */
        padding: 0px 10px;
    }
    .lengh-limit{
        display: block;
        width: 100%;
        overflow: hidden;
        white-space: nowrap;
        text-overflow: ellipsis;
    }
    @media (min-width: 992px) {
        .mycol-md-1
        {
            width: 125px!important;
        }
    }
    @media (max-width: 800px) {
        .colxs{
            padding-right: 0.8px!important;
            padding-left: 0.8px!important;
        }
    }
</style>
@section('main')
<div class="container">
    <main role="main">
                <div class="">
                    <div class="jumbotron text-center jumbo-image">
                        <div class="set-jumbo">
                            <h1>Discover Movies</h1>
                            <p>Discover the latest Movies and TV Shows being reliesed both locally and internationaly. See what movies are 
                            trending and <a href="#">Review and Rate</a> them</p> 
                            <p>You can also watch Free movies and TV Shows <a href="{{ route('movies.index') }}">here.</a>
                            <div class="j-divider"></div>
                            <medium class="by-country">
                                <a href="{{ route('usa') }}">Hollywood</a> &middot; <a href="{{ route('zm') }}">Zambian</a> &middot; <a href="{{ route('usa') }}">Nollywood</a> &middot; 
                                <a href="">Kenyan</a> &middot; <a href="">South African</a> &middot; <a href="">Tanzanyan</a> &middot; 
                                <a href="">German</a> &middot; <a href="">Mexico</a> &middot; <a href="{{ route('newz') }}">New Zealand</a> &middot; 
                                <a href="{{ route('uk') }}">British</a> &middot; <small><a href="" class="text-info text-lg">More &raquo;</a> </small>
                            </medium>
                            <div class="j-divider"></div>
                        </div>
                    </div>
                </div>

        <!-- Side begins here
            <aside class=" col-md-3 col-sm-12 col-xs-12 sidenav side-bg">
                <div style="padding: 15px;">
                    <div class="p-3 mb-3 bg-light rounded">
                        <h4 class="font-italic">Upcoming Events</h4>
                        <ol class="list-unstyled mb-0">
                        <li><a href="#">The Jema Fest</a></li>
                        <li><a href="#">All White Party</a></li>
                        <li><a href="#">Kaya film Festival</a></li>
                        </ol>
                    </div>

                    <div class="p-3">
                        <h4 class="font-italic">Headlines This Month</h4>
                        <ol class="list-unstyled mb-0">
                        <li><a href="#">Comic coast deadlk</a></li>
                        <li><a href="#">Comic coast deadlk</a></li>
                        <li><a href="#">Comic coast deadlk</a></li>
                        </ol>
                    </div>

                    <div class="p-3">
                        <h4 class="font-italic">Movies Around The World</h4>
                        <ol class="list-unstyled">
                        <li><a href="#">Comic coast deadlk</a></li>
                        <li><a href="#">Comic coast deadlk</a></li>
                        </ol>
                    </div>

                    <div class="p-3">
                        <h4 class="font-italic">Elsewhere</h4>
                        <ol class="list-unstyled">
                        <li><a href="#">Twitter</a></li>
                        <li><a href="#">Facebook</a></li>
                        </ol>
                    </div>
                </div>
            </aside>
        Sidebar ends here-->
        <!-- Sidebar for the blo -->

        <div class="">       
        @foreach($titles as $title)
        @if($title !== '')
        <div class="text-center">
            <div class=" panel pster col-sm-3 col-xs-3 mycol-md-1 colxs"> 
                <a href="./titles/{{ $title->id }}" class="">
                    <img class="img-rounded title-frame" alt="{{ $title->name }}" title="{{ $title->name }}" src="{!! $imgbaseurl,$imgsize,$title->poster !!}" style="height: 140px; width: 100%; display: block;"> 
                </a>
                <div class="card-body m-b-md">
                    <div class="card-text links">
                        <span class="title"><a href="#"><strong class="lengh-limit">{{ $title->name }}</strong></span>
                         <div class="lengh-limit">
                            {{ \Carbon\Carbon::parse($title->release_date)->format('Y') }}
                         </div>
                        <div class="btn-group btn-group-xs">
                            <button type="button" class="btn btn-default"><a href="./titles/{{ $title->id }}">View</a></button>
                        </div>
                    </div>
                </div>
                <!-- Lil Xperiment ends here-->
            </div>
        </div>
        @else       @endif
        @endforeach
        </div>
 
        <div class="">       
        @foreach($mytitles as $title)
        @if($title !== '')
        <div class="text-center">
            <div class=" panel pster col-sm-3 col-xs-3 mycol-md-1 colxs"> 
                <a href="./show_mytitle/{{ $title->id}}" class="">
                    <img class="img-rounded title-frame" alt="{{ $title->name }}" title="{{ $title->name }}" src="./storage/titles/posters/{{ $title->poster }}" style="height: 140px; width: 100%; display: block;"> 
                </a>
                <div class="card-body m-b-md">
                    <div class="card-text links">
                        <span class="title"><a href="#"><strong class="lengh-limit">{{ $title->name }}</strong></span>
                         <div class="lengh-limit">
                            {{ \Carbon\Carbon::parse($title->release_date)->format('Y') }}
                         </div>
                        <div class="btn-group btn-group-xs">
                            <button type="button" class="btn btn-default"><a href="./show_mytitle/{{ $title->id}}">View</a></button>
                        </div>
                    </div>
                </div>
                <!-- Lil Xperiment ends here-->
            </div>
        </div>
        @else       @endif
        @endforeach
        </div>
    

    </main>
</div>
@guest

@else
        @if(Auth::User()->role_id == 1)
                <div class="container">
                    <div class="pull-right">
                        <button><a href="{{url('/save')}}">Save</a></button>
                        <button><a href="{{url('/update')}}">Update - with detailes</a></button>
                    </div>
                </div>
        @endif
@endguest
@endsection

resources/views/titles/show.blade.php
@extends('layouts.dm')

    <title>View {{ $title->name }}</title>

    <link href="{{ asset('css/showtitle.css') }}" rel="stylesheet">
    <style>
    /**
    *Custon css code goes here..
    */
    .setjumbo{
            margin-top: 2px;
            /* margin-left: -60px; */
            color: white;
            background-color: #07bc4c;
            background-attachment: relative;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
            background-position: center center;
            height: 86%;
            width: 100%;
        }
    </style>

@section('main')

<div class="container">
        <div class="setjumbo text-left img-rounded"> <!--jum-->
            <div class="row jumbo-row">
                        <div class="col-md-4 col-xs-12">
                            <div class="card mb-4 box-shadow">
                                <img class="card-img-left img-rounded" alt="Thumbnail" style="height: 100%; width: 100%; display: block;" src="{!! $imgbaseurl,$imgsize,$title->poster !!}" data-holder-rendered="true">
                            </div>
                        </div>


                <div class="col-md-7 col-xs-12 xm-color">
                    <div class=" mb-4 box-shadow">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="text-center title-row"><strong class="title">{{ $title->name }}</strong> ({{ \Carbon\Carbon::parse($title->release_date)->format('Y') }})</div>
                        </div>

                        <div class="description col-md-12 col-xs-12">
                            <div class="well well-sm test" style=""> <p> {{ $title->description }} </p> </div>
                            <h4 class="text-center team-header"> </h4>
                        
                            
                        </div>
                    </div>
                </div>

            </div>
        </div>

                                <!-- Trailer-->
                            <div class="media text-center">
                                <div class="media-body">
                                    <iframe width="620" height="400" src="" frameborder="0" allowfullscreen>
                                    </iframe>
                                </div>
                            </div>

        <hr class="j-divider"> <!-- Additional Info -->

        <div class="row cast">
                <div class="text-center show-title-header lead">Additional Infomation</div>
            <div class="text-center">

                <div class="col-md-3 col-sm-6 col-xm-12">
                <p><span class="adi-info-lebo"><b>Year : </b></span> <span class="adi-info-lebo text-left"> {{ \Carbon\Carbon::parse($title->release_date)->format('Y') }}</span></p>
                <p><span class="adi-info-lebo"><b>Budget </b></span> <span class="adi-info-lebo text-left">{{ $title->budget}}</span></p>
                </div><!-- /.col-lg-3 -->

                <div class="col-md-3 col-sm-4 col-xs-12">
                <p><span class="adi-info-lebo"><b>Runtime </b></span> <span class="text-left adi-info-lebo">{{ $title->runtime }} <small>minutes</small></span></p>
                <p><span class="adi-info-lebo"><b>Languages </b></span> <span class="text-left adi-info-lebo">{{ $title->languages }} </span></p>
                </div><!-- /.col-lg-3 -->
            
                <div class="col-md-3 col-sm-6 col-xm-12">
                <p><span class="adi-info-lebo"><b>Country </b></span> <span class="text-left adi-info-lebo">{{ $title->country }}</span></p>
                <p><span class="adi-info-lebo"><b>Studio </b></span> <span class="text-left adi-info-lebo">{{ $title->studio }}</span></p> 
                </div><!-- /.col-lg-3 -->
            
                <div class="col-md-3 col-sm-6 col-xm-12">
                <p><span class="adi-info-lebo"><b>Revenue </b></span> <span class="text-left adi-info-lebo">{{$title->revenue}}</span></p>
                <p><span class="adi-info-lebo"><b>Genera </b></span> <span class="text-left adi-info-lebo"> {{ $title->genres }}</span></p>
                </div><!-- /.col-lg-3 -->
            
            </div>
        </div>

                                    <hr class="j-divider"><!-- CAst Div -->
    
        <div class="row cast">
                                    <div class="text-center Show-title-header lead"> Cast </div>
            <div class="roll">
            @foreach($cast as $actor)
                <div class="actor-line">
                    <div class=" col-md-2 col-sm-4 col-xs-4">
                        <!--a href="https://api.themoviedb.org/3/person/{{$actor['id']}}/images?api_key=487fab9ddd30a7c5518757cf04cb2f2e"-->
                        <img class="img-circle" src="{!! $imgbaseurl,$imgsize,$actor['profile_path'] !!}" alt="{{ $actor['name'] }}" width="120" height="120">
                        <h4 class="lengh-limit">{{ $actor['name'] }}</h4>
                        </a>
                        <h5 class="lengh-limit">As {{ $actor['character'] }} </h5>
                    </div>
                </div>
            @endforeach
            </div>
        </div>


                                        <hr class="j-divider"><!-- Images -->

        <div class="row cast">
                                        <div class="text-center Show-title-header lead">Screen Shots </div>
            <div class="roll">
            
                <div class="actor-line">
                    <div class=" col-md-2 col-sm-4 col-xs-4">
                        <!--a href="https://api.themoviedb.org/3/person/{{$actor['id']}}/images?api_key=487fab9ddd30a7c5518757cf04cb2f2e"-->
                        <img class="img-circle" src="!! $imgbaseurl,$imgsize,$actor['profile_path'] !!" alt=" " width="120" height="200">
                        <h4> </h4>
                        </a>
                        <h5> </h5>
                    </div>
                </div>
            
            </div> 
        </div>

                                        <hr class="j-divider"><!-- Simillar -->
        <div class="row cast">
                                        <div class="text-center Show-title-header lead">More Movies Like {{$title->name}} </div>
                <div class="roll">
                @foreach($similar as $title)
                    <div class="actor-line">
                        <div class="col-lg-3">
                            <a href="../titles/{{$title->id}}">
                                <img class="img-rounded" src="{!! $imgbaseurl,$imgsize,$title->poster !!}" alt="{{$title->name}}" width="144" height="200">
                            </a>
                            <h4><a class="lengh-limit" href="#">{{$title->title}}</a></h4>
                        </div><!-- /.col-lg-3 --> 
                    </div>    
                @endforeach
                </div>
        </div>

                                        <hr class="j-divider"> <!-- Studio -->
        <div class="row cast">
                                        <div class="text-center Show-title-header lead">More Movies by {{$title->studio}}</div>
                <div class="roll">
                @foreach($sameStudio as $title)
                    <div class="actor-line">
                        <div class="col-lg-3">
                            <a href="../titles/{{$title->id}}">
                                <img class="img-rounded" src="{!! $imgbaseurl,$imgsize,$title->poster !!}" alt="{{$title->name}}" width="144" height="200">
                            </a>
                                <h4><a class="lengh-limit" href="#">{{$title->title}}</a></h4>
                        </div>
                    </div>
                @endforeach
                </div>
        </div>

            <hr class="j-divider"> <!-- Studio -->
            
</div>


@endsection

resources/views/titles/uploadimg.blade.php
@extends('layouts.b4')

<title>DM - Upload Title Cont'd</title>
<link href="https://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
    <!--select country stuff-->
@section('main')
  <br />
  <div class="container">
    <div class="row justify-content-md-center">

      <div class="col-md-offset-3 col-md-6">

      @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div>
      @endif

                <h5>Great! Now add some promotional images for your awesome movie to finish uploading!</h5>

        <form method="post" action="{{ route('storeimages') }}" enctype="multipart/form-data" class="">
                  {{ csrf_field() }}


                        <hr>
                          <div class="form-group">
                                <label for="images">
                                    Choose Movie Promotional Images and Screenshots!
                                </label>
                                <input type="file"
                                        id="images"
                                        name="images[]"
                                        multiple="true"
                                        />
                          </div>
                        <hr>

                          <div class="form-group">
                                    <input type="hidden"
                                        name="mytitle_id"
                                        value="{{$mytitle_id}}"
                                        />
                          </div>

                          <div class="form-group">
                                <input type="submit" class="col-md-12 btn btn-sm btn-primary"
                                       value="Submit"/>
                          </div>
                          

                          <hr> <br \>
                
        </form>


      </div>
    </div>
  </div>

@endsection